#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t todo:t |:t
#+OPTIONS: toc:nil
#+OPTIONS: html-link-use-abs-url:nil html-postamble:auto
#+OPTIONS: html-preamble:t html-scripts:nil html-style:nil
#+OPTIONS: html5-fancy:t tex:t
#+HTML_DOCTYPE: html5
#+HTML_CONTAINER: div
#+DESCRIPTION:
#+KEYWORDS:
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+SUBTITLE:
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./stylesheet.css" />
#+HTML_HEAD_EXTRA:
#+INFOJS_OPT:
#+CREATOR: <a href="http://www.gnu.org/software/emacs/">Emacs</a> 26.0.90 (<a href="http://orgmode.org">Org</a> mode 9.0)
#+LATEX_HEADER:

#+TITLE: annotate.mattgauger.com - about
#+DATE: <2017-11-12 Sun>
#+AUTHOR: Matt Gauger
#+EMAIL: matt.gauger@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.0.90 (Org mode 9.0)

[[file:index.html][Home]]

I am [[http://mattgauger.com][Matt Gauger]]. In addition to [[http://blog.mattgauger.com][my blog]], I wanted to share links, shorter thoughts, and write book reviews somewhere.

There's a line in [[http://www.antipope.org/charlie/blog-static/fiction/accelerando/accelerando.html][Accelerando]] by Charles Stross that says the main character Manfred Macx:

#+BEGIN_QUOTE
... speed reads a new pop-philosophy tome while he brushes his teeth, then blogs his web throughput to a public annotation server
#+END_QUOTE

This is my own public annotation server. But beyond science fiction, I also realized that I am frequently sharing the same link to multiple people, and wanted to consolidate those shared links somewhere. I also wanted to track what books I was reading and potentially write mini-reviews of them. This serves as a public interface to my [[http://alumni.media.mit.edu/~rhodes/Papers/remembrance.html][Remembrance Agent]].

Note: Links to Amazon do not contain affiliate marketing links. All opinions are my own.
