#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t todo:t |:t
#+OPTIONS: toc:nil
#+OPTIONS: html-link-use-abs-url:nil html-postamble:auto
#+OPTIONS: html-preamble:t html-scripts:nil html-style:nil
#+OPTIONS: html5-fancy:t tex:t
#+HTML_DOCTYPE: html5
#+HTML_CONTAINER: div
#+DESCRIPTION: A page for links, book reviews, videos to share, and so on.
#+KEYWORDS:
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./stylesheet.css" />
#+HTML_HEAD_EXTRA:
#+SUBTITLE:
#+INFOJS_OPT:
#+CREATOR: <a href="http://www.gnu.org/software/emacs/">Emacs</a> 26.0.90 (<a href="http://orgmode.org">Org</a> mode 9.0)
#+LATEX_HEADER:

#+TITLE: annotate.mattgauger.com
#+DATE: <2017-11-12 Sun>
#+AUTHOR: Matt Gauger
#+EMAIL: matt.gauger@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.0.90 (Org mode 9.0)

[[file:about.html][About]]

* [[https://www.wired.com/story/inside-the-race-to-build-a-brain-machine-interface/][Inside the race to hack the human brain]] <wired.com> [2017-11-23 Thu 15:58]

Neuroprosthetics are on their way, possibly sooner than you think. And they won't necessarily require surgery:

#+BEGIN_QUOTE
... but he knows he’ll never sell a mass-market product that depends on drilling holes in people’s skulls. Instead, the algorithm will eventually connect to the brain through some variation of noninvasive interfaces being developed by scientists around the world, from tiny sensors that could be injected into the brain to genetically engineered neurons that can exchange data wirelessly with a hatlike receiver.
#+END_QUOTE



* [[http://www.rollingstone.com/culture/features/elon-musk-inventors-plans-for-outer-space-cars-finding-love-w511747][Elon Musk: The Architect of Tomorrow]] [2017-11-23 Thu 14:51]

A look into the mind of Elon Musk. Check out Ashlee Vance's book [[https://www.goodreads.com/book/show/22543496-elon-musk][Elon Musk: Inventing the Future]] for more background, if you haven't. There's also an extensive 4-part series on the [[https://waitbutwhy.com/2015/05/elon-musk-the-worlds-raddest-man.html][Wait but Why]] blog.

* [[http://www.transcendencecorporation.com/files/pdf/RULES.pdf?__s=6mbvgwtoyk5stqzz3xvi][Business Rules as Objects (Title: Self Evaluating Rules)]] paper [2017-11-20 Mon 13:43]

If you've coded a business rule soup in methods for your OOP classes, and felt like it quickly became unmaintainable or something that you can no longer reason about, this might be an interesting read.

* [[http://web.mit.edu/2.75/resources/random/How%2520Complex%2520Systems%2520Fail.pdf][How Complex Systems Fail]] paper [2017-11-20 Mon 13:42]

Some light reading for your Monday.

* [[https://disaster.radio/][disaster.radio]] [2017-11-18 Sat 08:20]

Another project attempting to build mesh networks with cheap/simple components and open source. This one uses ESP8226 boards and LoRa transceivers -- so it might not have a lot of bandwidth but it should have some range and usefulness in the intended situation of disaster recovery. This project comes from [[https://sudoroom.org/wiki/Mesh][SudoRoom makerspace]] and they have their own community mesh network built on OpenWRT, too: [[https://github.com/sudomesh/makenode][https://github.com/sudomesh/makenode]]

* [[https://en.wikipedia.org/wiki/Second-system_effect][Second-system effect]] [2017-11-18 Sat 00:21]

As made famous by Fred Brooks in [[https://en.wikipedia.org/wiki/The_Mythical_Man-Month][The Mythical Man-Month]]. See also [[http://catb.org/jargon/html/S/second-system-effect.html][second system effect]] entry on the Jargon file. Another link that I've shared enough over the past few weeks to warrant an entry here.

* [[http://orgmode.org/manual/Template-expansion.html#Template-expansion][Org mode template expansions]] [2017-11-17 Fri 17:10]

What I'm currently working on to get my workflow for [[http://annotate.mattgauger.com][annotate.mattgauger.com]] down to less keystrokes.

* [[https://www.jwz.org/doc/worse-is-better.html][The Rise of "Worse is Better"]] <2017-11-17 Fri 15:49>

by Richard Gabriel.

I had to share this at work again today, and I thought it was worth sharing here.

* [[https://www.kitchensoap.com/2012/10/25/on-being-a-senior-engineer/][On being a senior engineer]] <2017-11-16 Thu 10:02>

#+BEGIN_QUOTE
Being able to write a Bloom Filter in Erlang, or write multi-threaded C in your sleep is insufficient. None of that matters if no one wants to work with you.
#+END_QUOTE

* [[https://noflojs.org/][NoFlo - Flow-Based Programming for JavaScript]] <2017-11-16 Thu 16:52>

In the realm of different programming paradigms, here's a way to do data flow programming on Node. It even has a visual output for the graph of components. (But NoFlo is not, itself, a visual programming tool / visual block language.) This reminds me a lot of the data flow programming I did on [[http://hoplon.io/][Hoplon]], which is a data flow or "spreadsheet programming" library on ClojureScript.

* [[https://cloudplatform.googleblog.com/2017/01/availability-part-deux--CRE-life-lessons.html][SLOs, SLIs, SLAs, oh my - CRE life lessons]] <2017-11-16 Thu 16:38>

Continuing on the theme of designing and operating internet-scale systems. The entire [[https://landing.google.com/sre/book.html][Google SRE]] book, which I read back in September, is worth a read.

* [[http://static.usenix.org/event/lisa07/tech/full_papers/hamilton/hamilton_html/][On Designing and Deploying Internet-Scale Services]] <2017-11-15 Wed 10:45>

by James Hamilton - Windows Live Services Platform

Currently reading this and thought I'd share.

#+BEGIN_QUOTE
While auto-administration is important, the most important factor is actually the service itself. Is the service efficient to automate? Is it what we refer to more generally as operations-friendly? Services that are operations-friendly require little human intervention, and both detect and recover from all but the most obscure failures without administrative intervention. This paper summarizes the best practices accumulated over many years in scaling some of the largest services at MSN and Windows Live.
#+END_QUOTE

* [[http://babbagefiles.blogspot.com/2017/03/take-elfeed-everywhere-mobile-rss.html][Take Elfeed everywhere: Mobile rss reading Emacs-style (for free/cheap)]] <2017-11-14 Tue 20:56>

For those that still use subscribe to RSS and want something that goes from their local emacs to their smartphone.

* [[http://nautil.us/issue/53/monsters/the-last-invention-of-man][The Last Invention of Man - How AI might take over the world.]] <2017-11-14 Tue 20:45>
Some scifi for your day. By Max Tegmark, author if [[https://www.goodreads.com/book/show/34272565-life-3-0][Life 3.0]].

* [[https://olimex.wordpress.com/2017/10/12/teres-i-do-it-yourself-open-source-laptop-update/][TERES-I Do It Yourself Open Source Laptop update]] <2017-11-13 Mon 18:52>
A DIY laptop built with an ARM chip. Putting together a laptop from a kit sounds really appealing to me right now.

* [[https://www.staticgen.com]] <2017-11-12 Sun 17:46>
I looked at this list of static site generators before deciding to use Org mode to generate this page.

* [[https://github.com/gram-ai/radio-transformer-networks%0A][gram-ai/radio-transformer-networks]] <2017-11-12 Sun 17:46>
This could prove very interesting. DARPA issued [[https://spectrumcollaborationchallenge.com/][a Grand Challenge]] to use machine learning with software-defined radio a few years ago.
* 
